# Generated by Django 2.1.4 on 2019-01-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chavakali', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Visionimages',
        ),
    ]
