# Generated by Django 2.1.4 on 2019-01-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chavakali', '0002_auto_20190111_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Visionimages',
        ),
    ]
