# Generated by Django 2.1.4 on 2019-02-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chavakali', '0003_auto_20190112_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Mercy',
        ),
    ]
