# Generated by Django 2.1.4 on 2019-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chavakali', '0004_auto_20190207_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('prayerRequest', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Mercy',
            new_name='Mercyimageones',
        ),
    ]
