# Generated by Django 2.1.4 on 2019-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chavakali', '0005_auto_20190506_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=250)),
                ('speakers', models.CharField(max_length=750)),
            ],
        ),
    ]
