# Generated by Django 2.2.2 on 2019-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chavakali', '0006_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homemission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
