# Generated by Django 2.2.2 on 2019-06-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chavakali', '0010_couplescover_couplesfooter_menfooter_sundayschoolcover_sundayschoolfooter_teenscover_teensfooter_wom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wwwfooter',
            new_name='Wwncover',
        ),
        migrations.RenameModel(
            old_name='Wwwcover',
            new_name='Wwnfooter',
        ),
    ]
